In [1]:
import numpy as np

In [2]:
# 1, 2 ve 3 boyutlu diziler oluşturma

array_1d = np.array([1, 2, 3])
array_2d = np.array([[1, 2], [3, 4]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [3]:
# Dizilerin boyutlarını öğrenme

array_1d.ndim

1

In [4]:
array_3d.ndim

3

In [5]:
# Dizilerin şekillerini öğrenme

array_3d.shape

(2, 2, 2)

In [6]:
array_2d.shape

(2, 2)

In [43]:
# Dizilerin eleman sayısını öğrenme (len fonksiyonu ile farkını vurgulayarak)

len(array_2d)

2

In [8]:
array_2d.size

4

In [9]:
len(array_3d)

2

In [10]:
array_3d.size

8

In [11]:
# 0 (sıfır) ve 1'lerden oluşan çok boyutlu dizi oluşturma

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [16]:
# Belirli aralıkta ve adımda dizi oluşturma

np.arange(10, 51, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
# Boş (empty) dizi oluşturma

np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Dizi elemanlarının işlemleri

array= np.array([1, 2, 3, 4 ,5])

In [19]:
np.sum(array)

15

In [20]:
np.min(array)

1

In [21]:
np.max(array)

5

In [22]:
np.mean(array)

3.0

In [23]:
np.var(array)

2.0

In [24]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [25]:
np.cos(array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [26]:
np.square(array)

array([ 1,  4,  9, 16, 25])

In [27]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [28]:
# Belirli bir aralıkta eşit olarak dağılmış sayılardan oluşan bir dizi oluşturma

np.linspace(0,10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
# Random dizi oluşturma

np.random.rand(2,3)

array([[0.84176061, 0.9730388 , 0.04578969],
       [0.61088112, 0.74819351, 0.95314804]])

In [31]:
# Random int tipinde değerleri olan dizi oluşturma

np.random.randint(1,20, size=(2,3))

array([[12,  6, 19],
       [17,  6, 16]])

In [32]:
# İki dizinin toplamı, farkı, çarpımı ve bölümünü hesaplama

array1= np.array([[1,2], [3,4]])
array2= np.array([[5,6], [7,8]])

In [33]:
np.add(array1, array2)

array([[ 6,  8],
       [10, 12]])

In [34]:
np.subtract(array1, array2)

array([[-4, -4],
       [-4, -4]])

In [35]:
np.multiply(array1, array2)

array([[ 5, 12],
       [21, 32]])

In [36]:
np.divide(array1, array2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [37]:
# İki dizinin mantıksal operatörle ile karşılaştırılması

np.greater(array1, array2) # Array1'deki elemanlar Array2'deki elemanlardan büyük mü?

array([[False, False],
       [False, False]])

In [38]:
np.equal(array1, array2) # Array1'deki elemanlar Array2'deki elemanlarla eşit mi?

array([[False, False],
       [False, False]])

In [39]:
# Çok boyutlu bir dizinin belirli bir değerine erişme
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Belirli Değere Erişme:", array3d[1, 0, 2])  # 1. indeksli bloğun 0. satırı, 2. sütunu

Belirli Değere Erişme: 9


In [40]:
 array3d[:, :, 1] # Tüm blokların tüm satırları, 1. sütun

array([[ 2,  5],
       [ 8, 11]])

In [42]:
condition = array3d > 5  # 5'ten büyük elemanlar için koşul
print("Koşulu Sağlayan Elemanlar:", array3d)

Koşulu Sağlayan Elemanlar: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
